#pragma once
#define BOARD_DISPLAY_SIDE "RIGHT"
#define BOARD_STARTING_RIGHT_X 48
#define BOARD_STARTING_LEFT_X 3
#define BOARD_CONTROLS_LEFT_X_OFFSET 40
		
// min 2
#define BOARD_STARTING_Y 2

#define DETERMINE_BOARD (BOARD_DISPLAY_SIDE == "RIGHT" ? BOARD_STARTING_RIGHT_X : BOARD_STARTING_LEFT_X)

#define DEFAULT_TEXT_COLOR 7
#define DEFAULT_INTERSECTION_CHAR "0"

#define BLACK_TURN 0
#define WHITE_TURN 1